[package]
name = "kyoto"
version = "0.1.0"
edition = "2021"
description = "global tokio handle for side effects"

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1.29.1", features = ["full"] }
parking_lot = "0.12.1"